set(USERMOD_DIR ${CMAKE_CURRENT_LIST_DIR})
add_library(usermod_lightwave INTERFACE)
file(GLOB_RECURSE USERMOD_DIR ${CMAKE_CURRENT_LIST_DIR}/*.c)
target_sources(usermod_lightwave INTERFACE ${USERMOD_DIR})
target_include_directories(usermod_lightwave INTERFACE ${CMAKE_CURRENT_LIST_DIR})
target_compile_definitions(usermod_lightwave INTERFACE)
target_link_libraries(usermod INTERFACE usermod_lightwave)

# set(USERMOD_NAME lightwave)
# set(USERMOD_DIR ${CMAKE_CURRENT_LIST_DIR})
# file(GLOB USERMOD_SOURCES "${USERMOD_DIR}/*.c")
# target_sources(usermod INTERFACE ${USERMOD_SOURCES})
# target_include_directories(usermod INTERFACE ${USERMOD_DIR})

# set(USERMOD_NAME usermod_lightwave)
# set(USERMOD_DIR ${CMAKE_CURRENT_LIST_DIR})
# file(GLOB USERMOD_SOURCES "${USERMOD_DIR}/*.c")
# add_library(${USERMOD_NAME} INTERFACE)
# target_sources(${USERMOD_NAME} INTERFACE ${USERMOD_SOURCES})
# target_include_directories(${USERMOD_NAME} INTERFACE ${USERMOD_DIR})
# target_link_libraries(usermod INTERFACE ${USERMOD_NAME})

# set(USERMOD_DIR ${CMAKE_CURRENT_LIST_DIR})
# add_library(usermod_lightwave INTERFACE)
# file(GLOB_RECURSE USERMOD_DIR ${CMAKE_CURRENT_LIST_DIR}/*.c)
# target_sources(usermod_lightwave INTERFACE ${USERMOD_DIR})
# target_include_directories(usermod_lightwave INTERFACE ${CMAKE_CURRENT_LIST_DIR})
# target_compile_definitions(usermod_lightwave INTERFACE MODULE_LIGHTWAVE_ENABLED=1)
# target_link_libraries(usermod INTERFACE usermod_lightwave)