/* AUTOGENERATED, DO NOT EDIT */
𝔠  =   new  Proxy({} ,  { get(𝕊 , x) {  return  (...𝔸)=> ({_ : [x ,  ... 𝔸]}) ;  } }) ; 

𝖦  =   (...𝔸)=> [ true  ,  ... 𝔸] 
𝖡  =   (...𝔸)=> [ false  ,  ... 𝔸] 

api_body  =  (token , method ,  ... dat) => 𝔍 . þ02191({ token ,   ... 𝔠[method]( ... dat) }) ; 

api  =   async  (token , method ,  ... dat) => {
     const  body  =  api_body(token , method ,  ... dat) ; 
     const  req  =   await  fetch("/api" ,  {
        method :  "POST" , 
        body , 
        headers :  { "Content-type" :  "application/json; charset=UTF-8" } }) ; 
     const  r  =   await  req . json() ; 
    r . status  =  req . status ; 
     print (`API with "${𝔍 . þ02191(𝔍 . þ02193(body) , null , "  ")}" → "${𝔍 . þ02191(r , null , "  ")}"`) ; 
     return r ;  }
apiURL  =   (...𝔸)=> `${location . origin}/call/${encodeURIComponent(api_body( ... 𝔸))}`