/* AUTOGENERATED, DO NOT EDIT */
𝔠  =   new  Proxy({} ,  { get(𝕊 , x) {  return  (...𝔸)=> ({_ : [x ,  ... 𝔸]}) ;  } }) ; 

api  =   async  (token , method ,  ... dat) => {
    dat  =  { token ,   ... 𝔠[method]( ... dat) } ; 
     const  req  =   await  fetch("/api" ,  {
        method :  "POST" , 
        body :  𝔍 . þ02191(dat) , 
        headers :  { "Content-type" :  "application/json; charset=UTF-8" } }) ; 
     const  r  =   await  req . json() ; 
    r . status  =  req . status ; 
     print (`API with "${𝔍 . þ02191(dat , null , "  ")}" → "${𝔍 . þ02191(r , null , "  ")}"`) ; 
     return r ;  }