/* AUTOGENERATED */
api_body  =  (token , method ,  ... dat) => 𝔍 . þ02191({ token ,   ... 𝔠[method]( ... dat) }) ; 
api_URL  =   (...𝔸)=> `${location . origin}/call/${encodeURIComponent(api_body( ... 𝔸))}`
api  =   async  (token , method ,  ... dat) => {
     const  body  =  api_body(token , method ,  ... dat) ; 
     const  req  =   await  fetch("/api" ,  {
        method :  "POST" , 
        body , 
        headers :  { "Content-type" :  "application/json; charset=UTF-8" } }) ; 
     const  r  =   await  req . json() ; 
    r . status  =  req . status ; 
     print (`API with "${𝔍 . þ02191(𝔍 . þ02193(body) , null , "  ")}" → "${𝔍 . þ02191(r , null , "  ")}"`) ; 
     return r ;  }

layout_from_tok  =  (𝐭) => {
   if ( ! (𝐭 in 𝘋𝘉)) { 𝘋𝘉[𝐭] = { scenes : {} ,  devs : {} } ; 
               updateDB() ;  }
   return 𝘋𝘉[𝐭] ;  }
load_devices  =   async  (𝐭) => {
   const  𝐋  =  layout_from_tok(𝐭)
   let  r ; 
  try{ r  =   await  api(𝐭 , "Get_devs") ;  }catch(e){}
   if ( ! r[0]  ||  r . status != 200)  return 𝖡(𝐋 . devs) ; 
  𝐋 . devs  =  {  ... 𝐋 . devs ,   ... r[1] }
  updateDB() ; 
   return 𝖦(𝐋 . devs) ;  }

n2rgb  =   (x,...𝔸)=> [x >> 0 & 7 , x >> 8 & 7 , x >> 16 & 7] . ᴍ( (x,...𝔸)=> "RGB"[x]) . join( "" )