/* AUTOGENERATED */
RGB_calibrate  =   async  (𝐝) => {
   let  C  =  [ ... "RGB"] ; 
   await  𝐝 . bulk([`config` ,  { RGB_ORDER : `RGB` }] , 
           [`scene`  ,  { _singlecolor0 :  {fx : [[2 , 0.25]] , 1 : [300 , 0 , 255 << 16]} , 
                        _singlecolor1 :  {fx : [[2 , 0.25]] , 1 : [300 , 0 , 255 <<  8]} }] , 
           [`scene`  ,  `_singlecolor0` ,  false  , -1]) ; 
   return [C ,  async (α) => { C  =  C . þF0232( (x,...𝔸)=> x != α) ; 
             await  𝐝 . scene(`_singlecolor1` ,  false  , -1) ; 
             return [C ,  async (β) => { C  =  α + β + C . þF0232( (x,...𝔸)=> x != β)[0] ; 
                       await  𝐝 . bulk([`config` ,  {RGB_ORDER : C}] , 
                               [`scene`  ,  `_default` ,  false  , -1]) ; 
                       return C }] ;  }] ;  } ; 
prompt_rgb_calibrate  =   async (𝐝 , cb) => {
   let  α , β ; 
   const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
              mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column;`} , [(mkə(`h1` ,  false  , `RGB Calibration`)) , (mkə(`□` , {[`𝑆`] : `height: 40px;`} , ``)) , ((α = mkə(`□` ,  false  , ``))) , ((β = mkə(`□` ,  false  , ``)))])) ; 
  
   const  Ғ  =   async  (x,...𝔸)=> {
    α . replaceWith(α = mkə(`h2` ,  false  , `Loading...`))
    β . replaceWith(β = mkə(`□` ,  false  , ``))
     const  V  =   await  x() ; 
     if (isStr(V)) { þ0E27F . close() ; 
                   return cb(V) ;  }
     const  [C , ƒ]  =  V ; 
    α . replaceWith(α = mkə(`h2` ,  false  , `Choose the color that is visible on your LED strip.`))
    β . replaceWith(β = mkə(`span` , {[`𝐶`] : `rgbButtons`} , C . ᴍ( (x,...𝔸)=> { const  þ0E27F = textButton(x ,  (...𝔸)=> Ғ( async  (...𝔸)=> ƒ(x))) ;  SAT(þ0E27F , `c` , x) ;   return þ0E27F}))) ; 
  } ; 
  Ғ( async  (...𝔸)=>  await RGB_calibrate(𝐝)) ;  }

led_calibrate  =  þF01EE((𝘴 , 𝘳) =>  async (𝐝 , cb) => {
   const  SCENE_CALIB  =   (x,...𝔸)=> ({"*" : [{1 : [x , 0 , 0xFF00]} , {1 : [1001 - x , 0 , 0xFF0000]}                 ]}) ; 
   const  SCENE_FINAL  =   (x,...𝔸)=> ({"*" : [{1 : [1 , 0 , 0xFF00]} , {1 : [   x - 2 , 0 , 0       ]} , {1 : [1 , 0 , 0xFF00]}]}) ; 
   const  MSG  =  `Is red visible at the end of the LED strip?` ; 
   let  𝔖  =  [[1 , 100 , 1000]] ; 
   let  first =  true  ; 
   while ( true ) {  let  [l , m , h]  =  𝔖 . at(-1) ; 
          await  𝐝 . bulk( ... first ? [[`config` ,  {LEDC : 1000}]] : [] , 
                  [`scene` ,  `_calib` , SCENE_CALIB(m) ,  false  , -1]) ; 
         first =  false  ; 
         𝘴(m , MSG , [ ...  þ1F0CC (𝔖) > 1 ? [`←`] : [] , `No` , `Yes`]) ; 
          let  r  =   await  𝘳() ; 
          if (r == `←`) { 𝔖 . pop() ;   continue  ;  }
          if (l < h  ) {  if (r == `No`) h  =  m ; 
                     else          l  =  m + 1 ; 
                    m  =   ~  ~ ((l + h) / 2) ;  }
          if (l == h  ) {  await  𝐝 . bulk(["config" ,  {LEDC : m}                   ] , 
                             ["scene"  ,  `_calib` , SCENE_FINAL(m) ,  false  , -1]) ; 
                    𝘴() ; 
                     return cb(l) ;  }
         𝔖 . push([l , m , h]) ;  } }) ; 
prompt_led_calibrate  =   async (𝐝 , cb) => {
   let  α , β ; 
   const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
              mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column;`} , [(mkə(`h1` ,  false  , `LED Count Calibration`)) , (mkə(`□` , {[`𝑆`] : `height: 40px;`} , ``)) , ((α = mkə(`□` ,  false  , ``))) , ((β = mkə(`□` ,  false  , ``)))])) ; 
   const  load  =   (...𝔸)=> { α . replaceWith(α = mkə(`h2` ,  false  , `Loading...`))
              β . replaceWith(β = mkə(`□` ,  false  , ``)) ;  }
  load() ; 
   const  [𝘴 , 𝘳]  =  led_calibrate(𝐝 ,  (x,...𝔸)=> (þ0E27F . close() , cb(x))) ; 
   while ( true ) {  let  v  =   await  𝘳() ; 
          if ( ! (v && v . length))  break  ; 
          const  [n , m , C]  =  v ; 
          const  P  =  𝗉() ; 
         α . replaceWith(α = mkə(`h2` ,  false  , `Testing ${n} LEDs - ${m}`))
         β . replaceWith(β = əbuttonBar( ... C . ᴍ( (x,...𝔸)=> [x ,  (...𝔸)=> P . r(x)]) )) ; 
          const  dec  =   await  P ; 
         load() ; 
         𝘴(dec) ;  } } ; 