/* AUTOGENERATED */
RGB_calibrate  =   async  (𝐝) => {
   await  𝐝 . scene({ _singlecolor0 :  {"fx" : [[2 , 0.25]] , "1" : [300 , 0 , 16711680]} , 
              _singlecolor1 :  {"fx" : [[2 , 0.25]] , "1" : [300 , 0 ,    65280]}}) ; 
   const  conf  =   async  (x,...𝔸)=> {  await  𝐝 . config({RGB_ORDER : "RGB"}) ; 
                await  𝐝 . scene(`_singlecolor${x}` , false ,  - 1) ;  } ; 
   let  C  =  [ ... "RGB"] ; 
   await  conf(0) ; 
   return [C ,  async (α) => { C  =  C . þF0232( (x,...𝔸)=> x != α) ; 
             await  conf(1) ; 
             return [C ,  async (β) => { C  =  C . þF0232( (x,...𝔸)=> x != β)[0] + β + α ; 
                       await  𝐝 . config({RGB_ORDER : C}) ; 
                       return C }] ;  }] ;  } ; 





