/* AUTOGENERATED */
RGB_calibrate  =   async  (𝐝) => {
   let  C  =  [ ... "RGB"] ; 
   await  𝐝 . bulk(["config" ,  { RGB_ORDER : "RGB" }] , 
           ["scene"  ,  { _singlecolor0 :  {fx : [[2 , 0.25]] , 1 : [300 , 0 , 255 << 16]} , 
                        _singlecolor1 :  {fx : [[2 , 0.25]] , 1 : [300 , 0 , 255 <<  8]} }] , 
           ["scene"  ,  `_singlecolor0` ,  false  , -1]) ; 
   return [C ,  async (α) => { C  =  C . þF0232( (x,...𝔸)=> x != α) ; 
             await  𝐝 . scene(`_singlecolor1` ,  false  , -1) ; 
             return [C ,  async (β) => { C  =  α + β + C . þF0232( (x,...𝔸)=> x != β)[0] ; 
                       await  𝐝 . config({RGB_ORDER : C}) ; 
                       return C }] ;  }] ;  } ; 

prompt_rgb_calibrate  =   async (𝐝 , cb) => {
   let  α , β ; 
   const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
              mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column;`} , [(mkə(`h1` ,  false  , `RGB Calibration`)) , (mkə(`□` , {[`𝑆`] : `height: 40px;`} , ``)) , ((α = mkə(`□` ,  false  , ``))) , ((β = mkə(`□` ,  false  , ``)))])) ; 
  
   const  Ғ  =   async  (x,...𝔸)=> {
    α . replaceWith(α = mkə(`h2` ,  false  , `Loading...`))
    β . replaceWith(β = mkə(`□` ,  false  , ``))
     const  V  =   await  x() ; 
     if (isStr(V)) { þ0E27F . close() ; 
                   return cb(V) ;  }
     const  [C , ƒ]  =  V ; 
    α . replaceWith(α = mkə(`h2` ,  false  , `Choose the color that is visible on your LED strip.`))
    β . replaceWith(β = mkə(`span` , {[`𝐶`] : `rgbButtons`} , C . ᴍ( (x,...𝔸)=> { const  þ0E27F = textButton(x ,  (...𝔸)=> Ғ( async  (...𝔸)=> ƒ(x))) ;  SAT(þ0E27F , `c` , x) ;   return þ0E27F}))) ; 
  } ; 
  Ғ( async  (...𝔸)=>  await RGB_calibrate(𝐝)) ;  }

LED_calibrate  =   async  (𝐝) => {
  
}





