/* AUTOGENERATED */
 const test_dat = {
   "fx": [
     [1, 0, 0]
   ],
   "*": [{
     "*": [{
       "1": [50, 0, 16711680]
     }, {
       "1": [50, 0, 65280]
     }, {
       "1": [50, 0, 255]
     }]
   }, {
     "fx": [
       [1, 25, 0]
     ],
     "*": [{
       "1": [5, 1, 3, 245, 50]
     }, {
       "1": [45, 0, 4456448]
     }]
   }, {
     "fx": [
       [1, 25, 0]
     ],
     "*": [{
       "1": [22, 1, 1, 245, 50]
     }, {
       "1": [15, 0, 17408]
     }]
   }, {
     "fx": [
       [1, 25, 0]
     ],
     "*": [{
       "1": [33, 1, 1, 245, 50]
     }, {
       "1": [25, 0, 68]
     }]
   }, {
     "fx": [
       [1, 25, 0]
     ],
     "*": [{
       "1": [2, 1, 1, 245, 50]
     }, {
       "1": [120, 0, 4456516]
     }]
   }]
 }

 const ətriLabel = (𝚑, ...𝔸) =>
   mkə(false, {
     [`𝑆`]: `min-height: ${𝚑}px;`
   }, [(mkə(false, {}, 𝔸)), (mkə(`svg`, {
     [`viewBox`]: `-1.05 -1 2 2`,
     [`preserveAspectRatio`]: `none`
   }, [(mkə(`path`, {
     [`d`]: `M1 -1 L-1 0 L1 1`,
     [`style`]: `fill:#0000;stroke:#FFF;stroke-width:0.05`
   }, ``))]))])

 const 𝘌atom = (Ѧ, [n, i, ...þF0832]) => {
   const 𝗆 = (x, ...𝔸) => mkə(false, {
     [`𝐶`]: `𝘌atom`,
     [`𝑆`]: `height: ${Ѧ . χ * n}px;` + `;` + x
   }, ``)
   if (i == 0) {
     const [𝚌] = þF0832;
     return 𝗆(`background-color: ${þ0E22B(𝚌)};`);
   } else if (i == 1) {
     const [seg, sat, val] = þF0832;
     return 𝗆(`background: ${þ0EF26grad(seg)};`);
   }
   return `󰤱`;
 };
 const 𝘌𝖬 = (Ѧ, þF0832, n = 0) => {
   const ətick = (𝚒, m = 40, b = 20) => {
     const [p, s] = [(Math.max)(1, 3 / 𝚒), b + m / 𝚒];
     const [l, α] = [255 - 40 * (𝚒 - 1), 100];
     const clr = `rgba(${l},${l},${l},${α}%)`;
     const cnd = 𝚒 > 1 ? `;pointer-events:none` : "";
     return mkə(false, {
       [`𝐶`]: `𝘌tickmark`,
       [`𝑆`]: `background-color: ${clr}; width: ${s}px; height: ${p}px; min-height: ${p}px; margin-bottom: ${ - p}px;` + cnd
     }, ``);
   };

   let C = `1` in þF0832 ? [𝘌atom(Ѧ, þF0832[`1`])] : þF0832[`*`].ᴍ((x, ...𝔸) => 𝘌𝖬(Ѧ, x, n + 1));
   C = C.ᴍ((x, y, ...𝔸) => (x.idx = y, x));
   if (C.length > 1) C = C.þ02A1D𝑙((...𝔸) => ətick(n + 1));

   let þ0E27F = mkə(false, {
     [`𝐶`]: `𝘌modes`
   }, C);

   if (!n && `*` in þF0832) {
     C.forEach((cþ0E27F) => {
       cþ0E27F = dragItem(cþ0E27F, n, (x, y, ...𝔸) => {
         swapə(x, y);
         const d = Ѧ.þF0832[`*`];
         [d[x.idx], d[y.idx]] = [d[y.idx], d[x.idx]];
         Ѧ.setPreview();
       });
       cþ0E27F.onclick = (...𝔸) => Ѧ.render(Ѧ.þF0832[`*`][cþ0E27F.idx]);
     });
   } else if (n > 1) þ0E27F.style.pointerEvents = `none`;
   if (!n) {
     þ0E27F.idx = 0;
     const x = QSAS(`.𝘌atom`, þ0E27F);
     x[0].toggleAttribute(`atom1`);
     x.at(-1).toggleAttribute(`atom󷰾`);
   }
   return þ0E27F;
 };

 const 𝘌setInspector = (Ѧ) => {
   const fx_og = ᴍv(þF0832Util.grpfx(Ѧ.þF0832), (x, ...𝔸) => x[0]);
   const fx = {
     0: [],
     1: [1, 0],
     2: [1],
     ...fx_og
   };

   let has_init = false;
   const check = (x, y, ...𝔸) => fx_togs[x][1].style.display != `none` ? [
     [y, ...fx[y]]
   ] : [];
   const update = (...𝔸) => has_init && (Ѧ.þF0832.fx = [...fx_togs.rev[0].S ? [
     [0]
   ] : [], ...check(`rot`, 1), ...check(`lum`, 2)]);

   const fx_togs = {
     rev: [toggleButton((x, ...𝔸) => update(), ``, ``, false, {
       init: false,
       polar: false
     })],
     rot: [toggleButton((x, ...𝔸) => (show(fx_togs.rot[1], x), update()), `󱦙`, `󱦙`, false, {
         init: false
       }),
       ((...𝔸) => {
         let [speedlþ0E27F, offstlþ0E27F] = [mkə(`T`, false, ``), mkə(`T`, false, ``)];
         const speedþ0F1DEþ0E27F = əslider({
           l: -200,
           v: fx[`1`][0],
           h: 200,
           s: 0.1,
           ƒ: (x, ...𝔸) => (speedlþ0E27F.innerText = `${fx[`1`] [0] = x} Pixels/s`, update())
         });
         const offstþ0F1DEþ0E27F = əslider({
           l: -1000,
           v: fx[`1`][1],
           h: 1000,
           s: 1,
           ƒ: (x, ...𝔸) => (offstlþ0E27F.innerText = `${fx[`1`] [1] = x} Pixels`, update())
         });
         return mkə(false, {
           [`𝐶`]: `𝘌fxSection`
         }, [(mkə(`label`, false, `Rotation`)), (mkə(false, false, [(mkə(`label`, false, `Speed`)), (speedlþ0E27F), (speedþ0F1DEþ0E27F)])), (mkə(false, false, [(mkə(`label`, false, `Offset`)), (offstlþ0E27F), (offstþ0F1DEþ0E27F)]))]);
       })()
     ],
     lum: [toggleButton((x, ...𝔸) => (show(fx_togs.lum[1], x), update()), `󰳲`, `󰳲`, false, {
         init: false
       }),
       ((...𝔸) => {
         let lumlþ0E27F = mkə(`T`, false, ``);
         const lumþ0F1DEþ0E27F = əslider({
           l: 0,
           v: fx[`2`][0] * 255,
           h: 255,
           s: 1,
           ƒ: (x, ...𝔸) => (lumlþ0E27F.innerText = `${ þ02B13 ((fx[`2`] [0] = x / 255) * 100)}%`, update())
         });
         return mkə(false, {
           [`𝐶`]: `𝘌fxSection`
         }, [(mkə(`label`, false, `Brightness`)), (lumlþ0E27F), (lumþ0F1DEþ0E27F)]);
       })()
     ]
   };
   [`rev`, `rot`, `lum`].forEach((x, y, ...𝔸) => fx_togs[x][0].set(y in fx_og));
   has_init = true;

   const set = (...𝔸) => Ѧ.þF0832[`1`] = [Ѧ.þF0832[`1`][0], ...𝔸];

   const 𝘈 = Ѧ.𝘈þ0E27F.Ѧ;

   let 𝚟þ0E22B = mkə(false, {}, false);
   if (`1` in Ѧ.þF0832) {
     𝚟þ0E22B = Ѧ.þF0832[`1`][1] == 0 ? 𝑖2þ0E22B(Ѧ.þF0832[`1`][2]) : [50, 50, 50];
     𝘈.setþ0E27F(``, əþ0E22Bþ0F1DE({
       v: 𝚟þ0E22B,
       ƒ: (x, ...𝔸) => set(0, þ0E22B2𝑖(x))
     }));

     𝘈.setþ0E27F(`󷸾`, mkə(`󰤱`, false, false));
     𝘈.setþ0E27F(``, mkə(`󰤱`, false, false));
   }

   const modes = 𝒪k(𝘈.𝙳);
   print(modes);
   𝘈.set(modes[`1` in Ѧ.þF0832 ? Ѧ.þF0832[`1`][1] + 1 : 0]);
   modes.forEach((x, y, ...𝔸) => print(𝘈.𝙳[x].𝚋.disabled = (`1` in Ѧ.þF0832) ^ !!y));
   Ѧ.𝘐þ0E27F.Ѧ.setþ0E27F(``, mkə(false, {}, [(mkə(`span`, {
     [`𝐶`]: `𝘌toggleSection`
   }, 𝒪v(fx_togs).ꟿ((x, y, ...𝔸) => x.þ0E27F))), (𝒪v(fx_togs).ᴍþF01A9((x, ...𝔸) => x.length == 2 ? [x[1]] : []))]));
   Ѧ.𝘐þ0E27F.Ѧ.setþ0E27F(`⯈`, mkə(`button`, {
     [`onclick`]: (...𝔸) => 𝘌run(Ѧ.þF0832, Ѧ.𝐬, Ѧ.𝔖)
   }, `Ⴝω󷱇𝑔`));
 };

 const CSS_valid_ungroup = `.𝘌modes[dragitem]:not(:has(>:only-child))`;

 const 𝘌setPreview = (Ѧ, dat) => {
   if (!dat) dat = Ѧ.þF0832;
   if (!Ѧ.þF0832𝘏.length || dat && Ѧ.þF0832𝘏.at(-1) !== dat)
     Ѧ.þF0832𝘏.push(Ѧ.þF0832 = dat);
   const stot = þF0832Util.len(Ѧ.þF0832);
   Ѧ.top = Ѧ.þF0832𝘏.length == 1;

   Ѧ.χ = (Math.max)(2, 2.5 * (window.outerHeight / window.outerWidth), 400 / (Math.max)(stot, Ѧ.top ? Ѧ.L.ſ((x, y, ...𝔸) => x + y, 0) / 5 : 0));

   Ѧ.labelsþ0E27F.replaceChildren(
     ...Ѧ.top ? þ021A8(þF147C(Ѧ.N, Ѧ.L)).ꟿ((i, [𝐧, n]) => ətriLabel(n * Ѧ.χ, mkə(`T`, false, `${𝐧}`), mkə(`T`, false, `${n} Pxl`))) :
     [ətriLabel(Ѧ.χ * stot, mkə(`T`, false, `${stot} Pxl`))]);
   Ѧ.pixelsþ0E27F.replaceChildren(Ѧ.þF0832þ0E27F = 𝘌𝖬(Ѧ, Ѧ.þF0832));
   Ѧ.𝘖.prvþ0E27F.disabled = Ѧ.top;
   Ѧ.𝘖.grpþ0E27F.disabled = `1` in Ѧ.þF0832 || Ѧ.þF0832[`*`].length <= 1;
   Ѧ.𝘖.ugpþ0E27F.disabled = !Ѧ.þ0E27F.querySelector(CSS_valid_ungroup);
   Ѧ.𝘖.delþ0E27F.disabled = `1` in Ѧ.þF0832 || Ѧ.þF0832[`*`].length <= 1;
 };

 prompt_editor = (cb, 𝔖, 𝐬) => {
   𝐬.dat = test_dat;
   const Ѧ = {
     𝔖,
     𝐬,
     N: 𝐬.𝐔.ᴍ((x, ...𝔸) => 𝔖.𝐃[x]?.NAME ?? x),
     L: 𝐬.𝐔.ᴍ((x, ...𝔸) => 𝔖.𝐃[x].LEDC),
     þF0832: 𝐬.dat,
     þF0832𝘏: [],
     𝘖: {},
     setPreview: (...𝔸) => 𝘌setPreview(Ѧ, ...𝔸),
     setInspector: (...𝔸) => 𝘌setInspector(Ѧ, ...𝔸),
     render: (...𝔸) => (Ѧ.setPreview(...𝔸), Ѧ.setInspector())
   };

   window.Ѧ = Ѧ;

   const tool = (𝗍) => {
     if (𝗍 == `←`) {
       Ѧ.þF0832𝘏.pop();
       return Ѧ.render(Ѧ.þF0832𝘏.pop());
     } else if (𝗍 == `+`) {
       Ѧ.render(𝑜Replace(Ѧ.þF0832, þF0832Util.add(Ѧ.þF0832, {
         "1": [50, 0, 0x7F7F7F]
       })));
       return [...Ѧ.pixelsþ0E27F.querySelectorAll(`.𝘌modes`)].at(-1).scrollIntoView();
     }
     const css = 𝗍 == `` ? CSS_valid_ungroup : `.𝘌pixels>.𝘌modes>.𝘌atom,.𝘌modes[dragitem],.𝘌atom[dragitem]`;

     if (𝗍 == ``)
       clickDetect(css, (𝚂þ0E27F) => {
         Ѧ.þ0E27F.removeAttribute(`𝘌toolmode`, "");
         if (!𝚂þ0E27F) return;
         const 𝙸 = 𝚂þ0E27F.ᴍ((x, ...𝔸) => x.idx);
         const r = [(Math.min)(...𝙸), (Math.max)(...𝙸)];
         r[1]++;
         Ѧ.þF0832[`*`].splice(r[0], r[1] - r[0], {
           "*": Ѧ.þF0832[`*`].slice(r[0], r[1])
         });
         Ѧ.render();
       }, Ѧ.þ0E27F, {
         "*": true
       });
     else clickDetect(css,
       (sþ0E27F) => {
         if (!sþ0E27F) return Ѧ.þ0E27F.removeAttribute(`𝘌toolmode`, "");
         if (𝗍 == `` || `󰆴` == 𝗍) {
           if (𝗍 == ``) þF0832Util.ungrp(Ѧ.þF0832, sþ0E27F.idx);
           else if (𝗍 == `󰆴`) þF0832Util.del(Ѧ.þF0832, sþ0E27F.idx);
           Ѧ.render();
           return Ѧ.þ0E27F.removeAttribute(`𝘌toolmode`, "");
         }

         const dþ0E27F = QSAS(`.𝘌atom`, sþ0E27F).at(-1);
         const A = þF0832Util.ends(`1` in Ѧ.þF0832 ? Ѧ.þF0832[`1`] : Ѧ.þF0832[`*`][sþ0E27F.idx])[1];

         let lþ0E27F, n;
         const þF0616þ0E27F = mkə(false, {
           [`𝐶`]: `resizer`
         }, [(mkə(`T`, {}, `󰮹`)), ((lþ0E27F = mkə(`T`, {}, false)))]);

         let 𝚙;
         const show = (Δ) => {
           const h = Ѧ.χ * þF0832Util.len(A);
           Δ = (Math.max)(Ѧ.χ * þ025A2(Δ / Ѧ.χ), Ѧ.χ - h);
           lþ0E27F.innerText = n = þ025A2((h + Δ) / Ѧ.χ);
           þF0616þ0E27F.style.top = `${𝚙 . b + Δ}px`;
           dþ0E27F.style.height = `${𝚙 . h + Δ}px`;
         };
         const 𝐮 = () => {
           𝚙 = þ0F06F(dþ0E27F);
           þF0616þ0E27F.style.left = `${𝚙 . l + 𝚙 . w}px`;
           show(0);
         };
         𝐮();

         SAT(þF0616þ0E27F, `draggable`, `true`);
         AEL(þF0616þ0E27F, `dragstart`, (𝜺) => {
           𝜺.dataTransfer.setDragImage(mkə(`img`, false, []), 0, 0);
           þF0616þ0E27F.setAttribute(`dragging`, "");
           𝐮();
         });
         AEL(þF0616þ0E27F, `dragend`, (𝜺) => {
           A[0] = n;
           þF0616þ0E27F.removeAttribute(`dragging`);
           sþ0E27F.removeAttribute(`detector`);
           sþ0E27F.removeAttribute(`noscale`);
           Ѧ.þ0E27F.removeAttribute(`𝘌toolmode`, "");
           Ѧ.render();
         });
         AEL(þF0616þ0E27F, `drag`, (𝜺) => {
           if (𝜺.y) show(𝜺.y - 𝚙.b);
         });
         sþ0E27F.after(þF0616þ0E27F);
         sþ0E27F.setAttribute(`detector`, "");
         sþ0E27F.setAttribute(`noscale`, "");
       },
       Ѧ.þ0E27F);
     Ѧ.þ0E27F.setAttribute(`𝘌toolmode`, "");
   };
   (Ѧ.þ0E27F = mkə(popup, {
     [`󰅙`]: `✓`,
     [`noAppend`]: `✓`
   }, [(mkə(false, {
     [`𝐶`]: `𝘌outer`
   }, [(mkə(`T`, false, `Scene Editor`)), (mkə(false, {
     [`𝐶`]: `𝘌inner`
   }, [(mkə(false, {
     [`𝐶`]: `𝘌preview`
   }, [(mkə(false, {
     [`𝐶`]: `multiButtonBar`
   }, [((Ѧ.𝘖.prvþ0E27F = mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: (...𝔸) => tool(`←`)
   }, `←`))), ((Ѧ.𝘖.rszþ0E27F = mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: (...𝔸) => tool(`󰡏`)
   }, `󰡏`))), ((Ѧ.𝘖.grpþ0E27F = mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: (...𝔸) => tool(``)
   }, ``))), ((Ѧ.𝘖.ugpþ0E27F = mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: (...𝔸) => tool(``)
   }, ``))), ((Ѧ.𝘖.addþ0E27F = mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: (...𝔸) => tool(`+`)
   }, `+`))), ((Ѧ.𝘖.delþ0E27F = mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: (...𝔸) => tool(`󰆴`)
   }, `󰆴`)))])), (mkə(false, {}, [(mkə(false, {}, [((Ѧ.labelsþ0E27F = mkə(false, {
     [`𝐶`]: `𝘌alignedLabels`
   }, false))), ((Ѧ.pixelsþ0E27F = mkə(false, {
     [`𝐶`]: `𝘌pixels       `
   }, false)))]))]))])), (mkə(false, {
     [`𝐶`]: `𝘌inspector`
   }, Ѧ.𝘐þ0E27F = ənavBar({
       Ⴝ: ``
     },
     [``, Ѧ.𝘈þ0E27F = ənavBar({
         Ⴝ: `G`
       },
       [`G`, mkə(false, {}, false)],
       [``, mkə(false, {}, false)],
       [`󷸾`, mkə(false, {}, false)],
       [``, mkə(false, {}, false)])],
     [``, mkə(false, {}, false)],
     [`⯈`, mkə(false, {}, false)])))]))]))]));
   Ѧ.þ0E27F.classList.add(`editorDialog`);
   Ѧ.render();

   þF0219.body.append(Ѧ.þ0E27F);
   Ѧ.þ0E27F.showModal();
 };