/* AUTOGENERATED */
 const CSS_valid_ungroup = `.𝘌modes[dragitem]:not(:has(>:only-child))`;

 𝔥 = (x, ...𝔸) => `calc(${x}px * var(--pxlSy))`;

 const ətriLabel = (𝚗, ...𝔸) =>
   mkə(false, [
     [`𝑆`, `min-height: ${𝔥(𝚗)}; height: ${𝔥(𝚗)}; max-height: ${𝔥(𝚗)};`]
   ], [(mkə(false, [], 𝔸)), (mkə(`svg`, [
     [`viewBox`, `-1.05 -1 2 2`],
     [`preserveAspectRatio`, `none`]
   ], [(mkə(`path`, [
     [`d`, `M1 -1 L-1 0 L1 1`],
     [`style`, `fill:#0000;stroke:#FFF;stroke-width:0.05`]
   ], ``))]))])

 const i2m = (x, ...𝔸) => 1 in Ѧ.þF0832 ? Ѧ.þF0832[1] : Ѧ.þF0832["*"][x];

 const əresizer = (Ѧ, 𝘔þ0E27F) => {
   let lþ0E27F;
   const þ0E27F = mkə(false, [
     [`𝐶`, `resizer`]
   ], [((lþ0E27F = mkə(`T`, false, print(þF0832Util.len(i2m(𝘔þ0E27F.idx))))))]);
   þ0E27F.dragstart = (𝜺) => {
     const y0 = 𝜺.Sy;
     const stot0 = Ѧ.stot;
     const M = i2m(𝘔þ0E27F.idx);
     const Mtot = þF0832Util.len(M);
     const A = þF0832Util.ends(M)[1];
     const Atot = þF0832Util.len(A);
     const 𝘈þ0E27F = 𝘔þ0E27F.þF7E04(`.𝘌atom`).at(-1);

     𝘔þ0E27F.𝙽 = (𝚗 = undefined) => {
       if (𝚗 === undefined) 𝚗 = Mtot;
       const Δ = 𝚗 - Mtot;
       A[0] = Atot + Δ;
       Ѧ.stot = stot0 + Δ;
       𝘈þ0E27F.style.height = 𝔥(Atot + Δ);
       lþ0E27F.innerText = 𝚗;
       print(`Δ=${Δ} (${A[0]} ${Ѧ . stot})`)
       scale();
       return 𝚗;
     }
     const update = (Δ) => {
       const n = þF7E44(Atot + þ025A2(Δ / Ѧ.ch * þ02908(100, þ02909(10, Ѧ.stot))), 1, MAX_LEDC);
       𝘔þ0E27F.𝙽(Mtot - Atot + n);
     };
     þ0E27F.drag = (𝜺) => 𝜺.Sy && update(𝜺.Sy - y0);
     þ0E27F.dragend = (𝜺) => {
       þ0E27F.þF15DF(`dragging`);
       Ѧ.setPreview();
     };
     þ0E27F.þF09E5(`dragging`);
   };
   return makeDraggable(þ0E27F);
 };

 const staggerþ0E749 = `repeating-linear-gradient(180deg,#0000,#0000 ${𝔥(1)},#0007 ${𝔥(1)},#0007 ${𝔥(2)})`

 const 𝘌atom = (Ѧ, [n, i, ...þF0832]) => {
   const 𝗆 = (x, ...𝔸) => mkə(false, [
     [`𝐶`, `𝘌atom`],
     [`𝑆`, `height: ${𝔥(n)};` + x]
   ], ``);
   const bgPfxþ0E749 = 1 in Ѧ.þF0832 ? staggerþ0E749 + "," : ""
   if (i == 0) {
     const [𝚌] = þF0832;
     const bgþ0E749 = ((x, ...𝔸) => `linear-gradient(0deg,${x})`)(þ0E22Bþ0E749(𝑖2þ0E22B(þF0832[0])));
     return 𝗆(`background:${bgPfxþ0E749}${bgþ0E749}`);
   } else if (i == 2) {
     let [_, Δ, ...𝙲] = þF0832;
     𝙲 = 𝙲.ᴍ(𝑖2þ0E22B);
     const γ = 1 - Δ;
     const [𝜟, 𝜸] = [Δ / 𝙲.length, γ / 𝙲.length];
     const 𝚠 = 𝜟 + 𝜸;
     const þ0E22Be = þ0E22Blerp(𝙲[0], 𝙲.at(-1), 0.5);
     const þF7E3E = [
       [þ0E22Be, 0],
       ...𝙲.ᴍþF01A9((þ0E22B, i) => [
         [þ0E22B, 𝜸 * 0.5 + i * 𝚠],
         [þ0E22B, 𝜸 * 0.5 + i * 𝚠 + 𝜟]
       ]),
       [þ0E22Be, 1]
     ];
     const bgþ0E749 = `linear-gradient(to bottom,${þF7E3E . ꟿ( (x,y,...𝔸)=> `${þ0E22Bþ0E749(x)} ${y * 100}%`) . join(",")})`;
     return 𝗆(`background:${bgPfxþ0E749}${bgþ0E749}`);
   } else if (i == 1) {
     const [seg, sat, val] = þF0832;
     return 𝗆(`background:${bgPfxþ0E749}${þ0EF26gradþ0E749( þ02909 (seg , 0.5) , sat , val)}`);
   }
 };

 const 𝘌bevelMode = (Ѧ) => {
   const 𝙰 = Ѧ.pixelsþ0E27F.þF7E02(`.𝘌atom`);
   const add = Ѧ.þF0832𝘏.length == 1 ? [`devLayer`] : []
   𝙰[0].þF09E5([`atom1`, ...add]);
   𝙰.at(-1).þF09E5([`atom󷰾`, ...add]);
 }

 const 𝘌𝖬 = (Ѧ, þF0832, n = 0) => {
   const ətick = (𝚗, m = 0, b = 1) => {
     const p = þ02909(1, 3 / 𝚗) / 100;
     const [l, α] = [255 - 40 * (𝚗 - 1), 255];
     const clr = þ0E22Bþ0E749([l, l, l, α]);
     const cnd = 𝚗 > 1 ? `;pointer-events:none` : "";
     return mkə(false, [
       [`𝐶`, `𝘌tickmark`],
       [`𝑆`, `background-color: ${clr}; height: ${p}em; min-height: ${p}em; margin-top: ${ - p / 2}em; margin-bottom: ${ - p / 2}em;` + cnd]
     ], ``);
   };

   let C = 1 in þF0832 ? [𝘌atom(Ѧ, þF0832[1])] : þF0832["*"].ᴍ((x, ...𝔸) => 𝘌𝖬(Ѧ, x, n + 1));
   C = C.ᴍ((x, y, ...𝔸) => (x.idx = y, x))
     .þ02A1D𝑙((...𝔸) => ətick(n + 1))
     .ᴍþF01A9((x, ...𝔸) => [x, ...n || x.classList.contains(`𝘌tickmark`) ? [] : [əresizer(Ѧ, x)]]);
   let þ0E27F = mkə(false, [
     [`𝐶`, `𝘌modes`]
   ], C);

   if (n == 0 && "*" in þF0832)
     C.forEach((cþ0E27F) => {
       if (!cþ0E27F.þF7DFD(`.𝘌modes,.𝘌atom`)) return;
       cþ0E27F.onclick = (...𝔸) => Ѧ.render(Ѧ.þF0832["*"][cþ0E27F.idx]);
       cþ0E27F = dragItem(cþ0E27F, n, (x, y, ...𝔸) => {
         swapə(x, y);
         const d = Ѧ.þF0832["*"];
         [d[x.idx], d[y.idx]] = [d[y.idx], d[x.idx]];
         Ѧ.setPreview();
       });
     });
   return þ0E27F;
 };

 const 𝘌setPreview = (Ѧ, dat) => {
   if (!dat) dat = Ѧ.þF0832;
   if (!Ѧ.þF0832𝘏.length || dat && Ѧ.þF0832𝘏.at(-1) !== dat)
     Ѧ.þF0832𝘏.push(Ѧ.þF0832 = dat);
   Ѧ.top = Ѧ.þF0832𝘏.length == 1;
   const tots = (1 in Ѧ.þF0832 ? [Ѧ.þF0832] : Ѧ.þF0832["*"]).ᴍ(þF0832Util.len);
   Ѧ.stot = tots.ſ((x, y, ...𝔸) => x + y, 0);
   scale();

   Ѧ.labelsþ0E27F.replaceChildren(...Ѧ.top ? þ021A8(þF147C(Ѧ.N, Ѧ.L)).ꟿ((i, [𝐧, n]) => ətriLabel(n, mkə(`T`, false, `${𝐧}`), mkə(`T`, false, `${n} Pxl`))) : []);
   Ѧ.pixelsþ0E27F.replaceChildren(Ѧ.þF0832þ0E27F = 𝘌𝖬(Ѧ, Ѧ.þF0832));
   𝘌bevelMode(Ѧ);
   Ѧ.𝘖.prvþ0E27F.disabled = Ѧ.top;
   Ѧ.𝘖.grpþ0E27F.disabled = 1 in Ѧ.þF0832 || Ѧ.þF0832["*"].length <= 1;
   Ѧ.𝘖.ugpþ0E27F.disabled = !Ѧ.þ0E27F.querySelector(CSS_valid_ungroup);
   Ѧ.𝘖.delþ0E27F.disabled = 1 in Ѧ.þF0832 || Ѧ.þF0832["*"].length <= 1;
 };