/* AUTOGENERATED */
 const 𝑖2þ0E22B = (x, ...𝔸) => [x >> 16 & 0xFF, x >> 8 & 0xFF, x >> 0 & 0xFF];
 const þ0E22B2𝑖 = (x, ...𝔸) => x[0] << 16 | x[1] << 8 | x[2];
 const þ0E22B = (x, ...𝔸) => `rgb(${x >> 16 & 0xFF},${x >> 8 & 0xFF},${x >> 0 & 0xFF})`;
 const þ0EF26grad = (x, ...𝔸) => `linear-gradient(180deg in hsl longer hue, hsl(0,100%,50%), hsl(360,100%,50%)) 0 0 / ${100 / x}% 100% repeat-x`;

 const show = (x, y, ...𝔸) => x.style.display = y ? "" : `none`;
 const clickDetect = (𝚚, ƒ, base = þF0219.body, Ѧ = {}) => {
   Ѧ = {
     "*": false,
     ...Ѧ
   };

   const Bþ0E27F = [mkə(`button`, {
     [`𝐶`]: `detectorMeta detectorCancel`,
     [`detector`]: `true`
   }, `←`)];
   if (Ѧ[`*`]) Bþ0E27F.push(mkə(`button`, {
     [`𝐶`]: `detectorMeta detectorSubmit`,
     [`detector`]: `true`
   }, `✓`));

   base.append(...Bþ0E27F);
   const 𝚂þ0E27F = [...base.querySelectorAll(𝚚)];
   const tog = () => 𝚂þ0E27F.ᴍþF01A9((x, ...𝔸) => {
     const r = HAT(x, `multidetect`);
     x.þF017A(`detector`);
     x.þF15DF(`multidetect`);
     return r ? [x] : [];
   });
   tog();
   const rem = AEL(þF0219, `click`, (ε) => {
     const cease = (...𝔸) => (Bþ0E27F.ᴍ((x, ...𝔸) => x.remove()), rem(), ƒ(...𝔸));
     ε.stopPropagation();
     ε.preventDefault();
     if (ε.target.closest(`.detectorSubmit`)) return cease(tog());
     if (ε.target.closest(`.detectorCancel`)) return tog(), cease();
     const þ0E27F = ε.target.closest(𝚚);
     if (!þ0E27F) return;
     if (Ѧ[`*`]) return þ0E27F.þF017A(`multidetect`);
     else return tog(), cease(þ0E27F);
   }, true);
   return rem;
 };

 əbigButton = (c, 𝔸) => mkə(`div`, {
   [`𝐶`]: `bigButton`,
   ...(𝔸)
 }, c)
 əbarButton = (c, 𝔸) => mkə(`span`, {
   [`𝐶`]: `hbar     `,
   ...(𝔸)
 }, c)

 əitemGridEditable = (plus, gen, rem, items = [], Ѧ = {
   show_plus: true,
   placeholder: undefined
 }) => {
   let þ0E27F, þ0E27F_adder;
   (þ0E27F = mkə(false, {
     [`𝐶`]: `itemGrid`
   }, [((þ0E27F_adder = mkə(false, {
     [`𝐶`]: `itemGridItem itemGridAdder`
   }, [(əbigButton(`+`, {
     onclick: () => plus(þ0E27F.add_item)
   }))])))]));
   þ0E27F.add_item = (x, y, ...𝔸) => {
     let newElm = mkə(`div`, {
       [`𝐶`]: `itemGridItem`
     }, false);
     if (y) {
       newElm.classList.add(`itemGridPlaceholder`);
       chainIntoElements(x, newElm);
     } else {
       chainIntoElements(gen(x, () => (rem(x), newElm.remove())), newElm);
     }
     newElm.ə = newElm.children[0]
     þ0E27F.insertBefore(newElm, þ0E27F_adder);
   };
   if (Ѧ.placeholder !== undefined) þ0E27F.add_item(Ѧ.placeholder(), true);
   þ0E27F.clear_items = () => QSA(`:scope > :not(:is(.itemGridAdder,.itemGridPlaceholder))`, þ0E27F).ᴍ((x, ...𝔸) => x.remove())
   þ0E27F.set_plus = (x, ...𝔸) => þ0E27F_adder.style.display = x ? `unset` : `none`;
   þ0E27F.set_plus(Ѧ.show_plus);
   items.forEach(þ0E27F.add_item);
   return þ0E27F;
 };

 ətitledBox = (𝚝, ə, Ѧ = {
     outline: true
   }) =>
   mkə(`div`, {
     [`𝐶`]: `titledBox`
   }, [(mkə(`h1`, false, [(𝚝)])), (mkə(false, {
     [`𝐶`]: `box${ ! Ѧ . outline ? ` noOutline` :  "" }`,
     [`𝑆`]: `overflow-x: hidden; overflow-y: auto;`
   }, [(ə)]))])

 əbuttonBar = (...𝔸) =>
   mkə(`span`, {
     [`𝐶`]: `multiButtonBar`
   }, 𝔸.ꟿ((x, y, ...𝔸) => mkə(`button`, {
     [`𝐶`]: `barButton`,
     [`onclick`]: y
   }, x)));
 ənavBar = (Ѧ, ...𝙴) => {
   𝙴 = 𝙴.ᴍ((x, ...𝔸) => x.nodeName != `✗` ? [x.þF1021(`󰊄`), x.children[0], (x.þF15DF(`󰊄`), x.þF1021())] : ["", x.children[0]]);

   Ѧ = {
     init: true,
     ƒ: þF0EFE,
     𝙳: {},
     ...Ѧ
   };
   const bar = [];
   for (let [k, e, ɒ = {}] of 𝙴)
     if (k) {
       const 𝚋 = mkə(`button`, {
         [`𝐶`]: `barButton`,
         [`onclick`]: (...𝔸) => þ0E27F.set(k),
         ...(ɒ)
       }, k)
       Ѧ.𝙳[k] = {
         þ0E27F: e,
         𝚋
       };
       bar.push(𝚋);
     }
   else {
     bar.push(e);
   }

   let holderþ0E27F, barþ0E27F;
   const þ0E27F = mkə(false, {
     [`𝐶`]: `navContainer`
   }, [((barþ0E27F = mkə(false, {
     [`𝐶`]: `multiButtonBar`
   }, bar))), ((holderþ0E27F = mkə(false, {
     [`𝐶`]: `navBodyHolder`
   }, Ѧ.placeholder ?? (mkə(`T`, false, ``)))))])
   Ѧ.update = Ѧ.multi ? (k) => {
       const s = Ѧ.Ⴝ.includes(k)
       if (s) {
         Ѧ.Ⴝ = Ѧ.Ⴝ.þF0232((x, ...𝔸) => x != k);
         RAT(Ѧ.𝙳[k].𝚋, `choosen`);
         holderþ0E27F.removeChild(Ѧ.𝙳[k].þ0E27F);
       } else {
         Ѧ.Ⴝ.push(k);
         SAT(Ѧ.𝙳[k].𝚋, `choosen`);
         holderþ0E27F.append(Ѧ.𝙳[k].þ0E27F);
       }
       return Ѧ.Ⴝ;
     } :
     (k = Ѧ.Ⴝ) => {
       RAT(Ѧ.𝙳[Ѧ.Ⴝ].𝚋, `choosen`, `disabled`);
       Ѧ.Ⴝ = k;
       [`choosen`, `disabled`].forEach((x, ...𝔸) => SAT(Ѧ.𝙳[Ѧ.Ⴝ].𝚋, x));
       holderþ0E27F.replaceChildren(Ѧ.𝙳[Ѧ.Ⴝ].þ0E27F);
       return Ѧ.Ⴝ;
     };
   þ0E27F.set = Ѧ.set = (...𝔸) => Ѧ.ƒ(Ѧ.update(...𝔸));

   Ѧ.setþ0E27F = (𝚔, þ0E27F) => Ѧ.𝙳[𝚔].þ0E27F.replaceWith(Ѧ.𝙳[𝚔].þ0E27F = þ0E27F);
   if (Ѧ.multi) {
     SAT(barþ0E27F, `plural`)
     const Ⴝ = Ѧ.Ⴝ;
     Ѧ.Ⴝ = [];
     Ⴝ.forEach((x, ...𝔸) => Ѧ.update(x));
   } else Ѧ.update();
   þ0E27F.Ѧ = Ѧ;
   if (Ѧ.init) Ѧ.ƒ(Ѧ.Ⴝ);
   return þ0E27F;
 }

 əslider = (Ѧ = {}) => {
   Ѧ = {
     init: true,
     l: 0,
     h: 100,
     s: 0,
     ƒ: þF0EFE,
     ...Ѧ
   };
   if (!(`v` in Ѧ)) Ѧ.v = Ѧ.l;
   [Ѧ.l, Ѧ.v, Ѧ.h, Ѧ.s] = [+Ѧ.l, +Ѧ.v, +Ѧ.h, +Ѧ.s];

   const þ0E27F = Ѧ.þ0E27F = mkə(`input`, {
     [`type`]: `range`,
     [`min`]: Ѧ.l,
     [`defaultValue`]: Ѧ.v,
     [`max`]: Ѧ.h,
     [`step`]: Ѧ.s
   }, ``);
   þ0E27F.value = Ѧ.v;
   Ѧ.set = (v = undefined) => {
     if (v === undefined) v = +þ0E27F.value;
     else þ0E27F.value = v;
     Ѧ.ƒ(Ѧ.v = v);
     return Ѧ.v;
   };
   AEL(þ0E27F, `input`, (...𝔸) => Ѧ.set());
   þ0E27F.Ѧ = Ѧ;
   if (Ѧ.init) Ѧ.set();
   return þ0E27F;
 }

 əþ0E22Bþ0F1DE = (Ѧ = {}) => {
   Ѧ = {
     init: true,
     v: [0, 0, 0],
     ƒ: þF0EFE,
     ...Ѧ
   };
   const 𝚂þ0E27F = [...`RGB`].ᴍ((x, y, ...𝔸) => mkə(əslider, {
     [`init`]: false,
     [`l`]: `0`,
     [`v`]: Ѧ.v[y],
     [`h`]: `255`,
     [`s`]: `1`,
     [`ƒ`]: () => Ѧ.set()
   }, false));
   const 𝙳þ0E27F = 𝚂þ0E27F.ᴍ((x, y, ...𝔸) => mkə(false, {}, [(mkə(`T`, false, [])), (x)]));
   const þ0E27F = mkə(false, {
     [`𝐶`]: `rgbSliders`
   }, 𝙳þ0E27F);
   Ѧ.update = (𝚟 = undefined) => {
     if (𝚟 === undefined) Ѧ.v = þ02B65(3).ᴍ((x, ...𝔸) => 𝚂þ0E27F[x].Ѧ.v);
     else(Ѧ.v = 𝚟).forEach((x, y, ...𝔸) => 𝚂þ0E27F[y].Ѧ.v = x);
     Ѧ.v.forEach((x, y, ...𝔸) => {
       const 𝚍 = 𝙳þ0E27F[y];
       𝚍.children[0].innerText = `${x}`;
       𝚍.style.backgroundColor = `rgb(${
                              y == 0  ? `${x},0,0` : 
                              y == 1  ? `0,${x},0` : 
                                   `0,0,${x}`     })`;
     });
     þ0E27F.style.backgroundColor = `rgb(${Ѧ . v . join(` `)})`;
     return Ѧ.v;
   };
   Ѧ.set = (...𝔸) => Ѧ.ƒ(Ѧ.update(...𝔸));
   Ѧ.update();
   þ0E27F.Ѧ = Ѧ;
   if (Ѧ.init) Ѧ.ƒ(Ѧ.v);
   return þ0E27F;
 }