/* AUTOGENERATED */


𝐴  =  𝒟([ ... `󰆴+󰐥󷹁`] . ᴍ(  (x,...𝔸)=> [x , `/Assets/${x}.svg`])) ; 

əti  =  (s , þF0284 =  false ) => þF0284 ? (mkə(`T` ,  false  , `${s}`)) : (mkə(`img` , {[`src`] : s} ,  false ))
əbigButton  =  (src , 𝔸 , þF0284 =  false ) => mkə(`div` , {[`𝐶`] : `bigButton` ,  ... (𝔸 )} , [(əti(src , þF0284))])
əbarButton  =  (src , 𝔸 , þF0284 =  false ) => mkə(`span` , {[`𝐶`] : `hbar     ` ,  ... (𝔸 )} , [(əti(src , þF0284))])
əbuttonBar  =   (...𝔸)=> 
  mkə(`span` , {[`𝐶`] : `multiButtonBar`} , 
    𝔸 . ꟿ( (x,y,z,...𝔸)=> mkə(`button` , {[`𝐶`] : `barButton` , [`onclick`] : y} , [(əti(x , z))]))) ; 

əitemGridEditable  =  (plus , gen , rem , items = [] , Ѧ = {show_plus :  true  , placeholder :  undefined }) => {
   let  ε , ε_adder ; 
  (ε = mkə( false  , {[`𝐶`] : `itemGrid`} , [((ε_adder = mkə( false  , {[`𝐶`] : `itemGridItem itemGridAdder`} , [(əbigButton(𝐴[`+`] ,  {onclick :   (...𝔸)=> plus(ε . add_item)}))])))])) ; 
  ε . add_item  =   (x,y,...𝔸)=> {  let  newElm  =  mkə(`div` , {[`𝐶`] : `itemGridItem`} ,  false ) ; 
                   if (y) { newElm . classList  . add(`itemGridPlaceholder`) ; 
                         chainIntoElements(x ,  newElm) ;  }
                   else     { chainIntoElements(gen(x ,  (...𝔸)=> (rem(x) , newElm . remove())) ,  newElm) ;  }
                  newElm . ə  =  newElm . children[0]
                  ε . insertBefore(newElm , ε_adder) ;  } ; 
   if (Ѧ . placeholder !==  undefined ) ε . add_item(Ѧ . placeholder() ,  true ) ; 
  ε . clear_items  =   (...𝔸)=> QSA(`:scope > :not(:is(.itemGridAdder,.itemGridPlaceholder))` , ε) . ᴍ( (x,...𝔸)=> x . remove())
  ε . set_plus  =   (x,...𝔸)=> ε_adder . style . display  =  x ? `unset` : `none` ; 
  ε . set_plus(Ѧ . show_plus) ; 
  items . forEach(ε . add_item) ; 
   return ε ;  } ; 

ətitledBox  =  (𝚝 , ə) => 
  mkə(`div` , {[`𝑆`] : `width: 80%; display: flex; flex-direction: column;`} , [(mkə(`h1` ,  false  , [(𝚝)])) , (mkə( false  , {[`𝐶`] : `box` , [`𝑆`] : `overflow-x: hidden; overflow-y: auto; padding-bottom: 10px;`} , [(ə)]))])