/* AUTOGENERATED */
𝗉  =   (x,...𝔸)=> {  let  r , p  =   new  Promise( (x,y,...𝔸)=> r = x) ; 
        return p . r = r , p ;  } ; 
𝘔  =   (...𝔸)=> { 
   const  M  =  [𝗉()] ; 
   const  𝘴  =   (...𝔸)=> (M . at(-1) . r(𝔸) , M . push(𝗉())) ; 
   const  𝘳  =   async  (...𝔸)=> ( (x,...𝔸)=> (M . shift() , x))( await  M[0])
   return [𝘴 , 𝘳] ;  } ; 
þF01EE  =  (ƒ) =>  (...𝔸)=> { 
   const  [[𝚂𝘴 , 𝙲𝘳] , [𝙲𝘴 , 𝚂𝘳]]  =  [𝘔() , 𝘔()]
  ƒ(𝚂𝘴 , 𝚂𝘳)( ... 𝔸) ; 
   return [𝙲𝘴 , 𝙲𝘳] ;  } ; 

fit_size  =  (𝐭 , w , sz = 100 , st =  ""  , Δ = 5) => {
   while (measureText(𝐭 , sz ,  "" ) . width >= w) sz  -=  Δ ; 
   return `font-size:${sz}px;` ;  } ; 

𝘋𝘉  =  𝔏𝔖 . þ02193("tokens" , {})
updateDB  =   (...𝔸)=> 𝔏𝔖 . þ02191("tokens" , 𝘋𝘉)
get_toks  =   (...𝔸)=> 𝒪k(𝘋𝘉)
layout_from_tok  =  (𝐭) => {
   if ( ! (𝐭 in 𝘋𝘉)) { 𝘋𝘉[𝐭] = { scenes : {} ,  devs : {} } ; 
               updateDB() ;  }
   return 𝘋𝘉[𝐭] ;  }
remove_tok  =  (𝐭) => {  print (`Deleting token "${𝐭}"`) ; 
                   delete  𝘋𝘉[𝐭] ; 
                  updateDB() ;  } ; 
load_devices  =   async  (𝐭) => {
   const  𝐋  =  layout_from_tok(𝐭)
   let  r ; 
  
  try{ r  =   await  𝐀(𝐭) . get_devs() ;  }catch(e){}
   if ( ! r  ||   ! r[0]  ||  r . status != 200)  return 𝖡(𝐋 . devs) ; 
  𝐋 . devs  =  {  ... ᴍv(𝐋 . devs ,  (x,y,...𝔸)=> [x , { ... y , offline :  false }]) ,   ... r[1] }
  updateDB() ; 
   return 𝖦(𝐋 . devs) ;  }