/* AUTOGENERATED */
𝘋𝘉  =  𝔏𝔖 . þ02193("tokens" , {})
updateDB  =   (...𝔸)=> 𝔏𝔖 . þ02191("tokens" , 𝘋𝘉)
layout_from_tok  =  (𝐭) => {
   if ( ! (𝐭 in 𝘋𝘉)) { 𝘋𝘉[𝐭] = { scenes : {} ,  devs : {} } ; 
               updateDB() ;  }
   return 𝘋𝘉[𝐭] ;  }
load_devices  =   async  (𝐭) => {
   const  𝐋  =  layout_from_tok(𝐭)
   let  r ; 
  
  try{ r  =   await  𝐀(𝐭) . get_devs() ;  }catch(e){}
   print (r) ; 
   if ( ! r  ||   ! r[0]  ||  r . status != 200)  return 𝖡(𝐋 . devs) ; 
  𝐋 . devs  =  {  ... ᴍv(𝐋 . devs ,  (x,y,...𝔸)=> [x , { ... y , offline :  false }]) ,   ... r[1] }
  updateDB() ; 
   return 𝖦(𝐋 . devs) ;  }