/* AUTOGENERATED */
BASE_CHARSET  =  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' ; 

þF0219  =  document ; 
[𝐴 , 𝐸 , 𝑜 ,  þ0221E ]  =  [Array , Element , Object , Infinity] ; 
[𝒪 , 𝒟 , 𝒪k , 𝒪v]  =  [𝑜 . entries , 𝑜 . fromEntries , 𝑜 . keys , 𝑜 . values] ; 
𝒪ℳ  =   (x,...𝔸)=> x .  ſ ( (x,y,...𝔸)=> ({ ... x ,  ... y})) ; 
𝔓  =   (x,...𝔸)=> x . prototype ; 
𝔍  =  {þ02191 : JSON . stringify ,  þ02193 : JSON . parse} ; 
 þF7E5D   =  String . fromCharCode ; 
 þ1F0CC   =   (x,...𝔸)=> x . length ; 
𝗙  =   (x,...𝔸)=> x instanceof Function ; 
𝑙  =   (x,...𝔸)=> [ ... x] ; 
 þF0EFE   =   (x,...𝔸)=> x ; 
 þF114F   =  Math . random ; 
[ þ02B13  ,  þ025A2  ,  þ02B12 ]  =  [Math . floor ,  Math . round ,  Math . ceil] ; 
[ (Math.max)  ,  (Math.min) ]  =  [Math . max , Math . min] ; 
 þF7E44       =   (x,y,z,...𝔸)=>  (Math.min) ( (Math.max) (x , y) , z)
 þ021A8   =   (x,...𝔸)=> [ ... x] . map((x , i) => [i , x])
 þ02B65   =   (x,y,...𝔸)=> isArr(x)  ? [ ... x . keys()] :   þ02B65 (Array(y ===  undefined  ? x : y - x)) . ᴍ((v) => v + (y ===  undefined  ? 0 : x)) ; 
 þF7E3B   =   (x,y,...𝔸)=> isArr(x)  ?  þ02B65 (a . length + 1) :  y ===  undefined   ?  þ02B65 (x + 1) :   þ02B65 (x , y + 1) ; 
 þF147C   =  ( ... 𝙰) =>  þ02B65 ( (Math.max) ( ... 𝙰 . ᴍ( þ1F0CC ))) . ᴍ((i) => 𝙰 . ᴍ( (x,...𝔸)=> x[i])) ; 
ᴍk  =   (x,y,...𝔸)=> 𝒟(𝒪(x) . ᴍ(([k , v]) => [y(k , v) , v])) ; 
ᴍv  =   (x,y,...𝔸)=> 𝒟(𝒪(x) . ᴍ(([k , v]) => [k , y(v , k)])) ; 
ᴍd  =   (x,y,...𝔸)=> 𝒟(𝒪(x) . ᴍ(([k , v]) => y(k , v))) ; 
𝒮  =  (d , k , v) => ( ! (k in d)  ||  d[k] === null)  ? (d[k] = v) :  d[k] ;  
 print       =  ( ... x) => (console . log  ( ... x) , x[0]) ; 
pairs  =   (x,...𝔸)=> x . toSpliced( - 1 , 1) . ᴍ((x , i) => [x , v[i + 1]]) ; 
table  =  ( ... x) => (console . table( ... x) , x[0]) ; 
ends   =  (l) => l . map((𝑥 , i) => [i == 0 , 𝑥 , i ==  þ1F0CC (l) - 1]) ; 
merge  =   (...𝔸)=> 𝑜 . assign({} ,  ... 𝔸) ; 
sleep  =  (s) =>  new Promise((r) => setTimeout(r , 1000 * s)) ; 
mk_id  =  (l , chars = BASE_CHARSET) =>  þ02B65 (l) . ᴍ( ()=> chars . at(Number( þF114F () *  þ1F0CC (chars)))) . ſ( (x,y,...𝔸)=> x + y ,   "" ) ; 
ƒdbg   =  (ƒ) =>  (...𝔸)=> {  print (`ƒ: Calling with:` ,  ... 𝔸) ; 
               const  r  =  ƒ( ... 𝔸) ; 
               print (`f: Returning` ,  r) ; 
               return r } ; 

𝔓(Number) . mod  =  function(n){  return (this % n + n) % n ;  } ; 

 þ0EB86   =  (x , ƒ   ) => { O  =  {} ; 
              x . forEach( (x,...𝔸)=> ((y) => y in O  ? O[y] . push(x) :  (O[y] = [x]))(ƒ(x ,  ... 𝔸))) ; 
               return O ;  } ; 
 Ϝ   =  (x , ƒ ,  ... 𝔸) => { 𝚁  =  [ ... 𝔸 ,  ... x] ; 
               for ( let  i = 𝔸 . length || 1 ;  i < 𝚁 . length ;  i ++ )
                𝚁[i]  =  ƒ(𝚁[i - 1] , 𝚁[i] , i)
              𝚁 . pop()
               return 𝚁 ;  } ; 
 const  arrayLike  =  {   þ0EB86  ,  Ϝ  , 
                 ᴍ :   (x,...𝔸)=> x . map    (        ... 𝔸) , 
                 þF01A9 :   (x,...𝔸)=> x . flat   (        ... 𝔸) , 
                ᴍþF01A9 :   (x,...𝔸)=> x . flatMap(        ... 𝔸) , 
                  ſ  :   (x,...𝔸)=> x . reduce (        ... 𝔸) , 
                  þF0232  :   (x,...𝔸)=> x . filter (        ... 𝔸) , 
                  þF7E3B  :   (x,...𝔸)=> x . slice  (        ... 𝔸) , 
                  ꟿ  :   (x,y,...𝔸)=> x . map    ( (x,...𝔸)=> y( ... x) ,  ... 𝔸) , 
                  þ022C0  :   (x,...𝔸)=> x . every  ( þF0EFE         ) , 
                  þ022C1  :   (x,...𝔸)=> x . some   ( þF0EFE         ) } ; 
arrayLike . þ02A1D𝑙  =   (x,y,...𝔸)=> [x[0] ,  ... x . þF7E3B(0 , -1) . ᴍþF01A9((c , i) => [y(c , x[i + 1]) , x[i + 1]])] ; 
𝒪(arrayLike) . forEach(([s , ƒ]) => {
  window[s]  =   (x,...𝔸)=> ƒ(isElement(x) ? 𝐴 . from(x) : x ,  ... 𝔸) ; 
  𝔓(𝐴)[s]  =  function( ... 𝔸){  return ƒ(       this  ,  ... 𝔸) ; } ; 
  𝔓(𝐸)[s]  =  function( ... 𝔸){  return ƒ(𝐴 . from(this) ,  ... 𝔸) ; } ;  }) ; 

AEL  =  (þ0E27F ,  ... 𝔸) => (þ0E27F . addEventListener( ... 𝔸) ,  ()=> REL(þ0E27F ,  ... 𝔸)) ; 
REL  =  (þ0E27F ,  ... 𝔸) => þ0E27F . removeEventListener( ... 𝔸) ; 
SAT  =  (x , y , z =  "" ) => x . setAttribute(y , z) ; 
HAT  =   (x,...𝔸)=> 𝔸 . ᴍ((a) => x . hasAttribute(a)) . þ022C0() ; 
RAT  =   (x,...𝔸)=> 𝔸 . forEach((a) => x . removeAttribute(a)) ; 
GID  =   (x,...𝔸)=> document . getElementById(x) ; 
VAL  =   (x,...𝔸)=> GID(x) . value ; 
QS   =  (x , ε = document) => ε . querySelector(x) ; 
QSA  =  (x , ε = document) => [ ... ε . querySelectorAll(x)] ; 
𝔏𝔖  =  { þ02191 :   (x,y,...𝔸)=> localStorage[x]  =  𝔍 . þ02191(y) , 
       þ02193 :   (x,y,...𝔸)=> x in localStorage ? 𝔍 . þ02193(localStorage[x]) : y , 
       þ02E13 :   (x,y,z,...𝔸)=> 𝔏𝔖 . þ02191(x ,  y(𝔏𝔖 . þ02193(x ,  z))) }

isStr  =   (x,...𝔸)=> typeof x  ===  "string" ; 
isNum  =   (x,...𝔸)=> typeof x  ===  "number" ; 
isArr  =   (x,...𝔸)=> x instanceof Array ; 
isElm  =   (x,...𝔸)=> x instanceof Element  ||  x instanceof HTMLDocument ;   
[isArray , isElement]  =  [isArr , isElm] ; 


chainIntoElements  =  (x , P) => {
     if ( ! (isArr(x)  ||  isStr(x)  ||  isElm(x)))
        x  =  [] ; 
     else    x  =  (isArr(x) ? x . þF01A9( þ0221E ) : [x])
               . ᴍ((𝚎) => isStr(𝚎)  ? þF0219 . createTextNode(𝚎) :  𝚎) ; 
     if (P ===  undefined )  return x
    P . append( ... x) ; 
     return P ;  }

 const  NSElmNames  =   new  Set(`svg g defs symbol use path rect circle ellipse line polyline polygon text tspan textPath linearGradient radialGradient stop pattern clipPath mask animate animateMotion animateTransform set metadata title desc view image foreignObject marker switch style` . split(` `)) ; 
mkə  =  (name , attrs , kids) => {
     const  remaps  =  { onclick : "onclick" ,  closedby : "closedBy" ,  NAME : "T" ,  𝑇𝐼 : "tabIndex" ,  𝑃𝐻 : "placeholder" ,  𝑇 : "type" ,  𝐼 : "id" ,  𝐶 : "className" } ; 
    kids  =  chainIntoElements(kids) ; 
     if (𝗙(name))  return name(attrs ,  ... kids) ; 
     if (name ===  false ) name  =  "div" ; 
     let  þ0E27F  =  NSElmNames . has(name)  ?  þF0219 . createElementNS(`http://www.w3.org/2000/svg` , name)
                                :  þF0219 . createElement(name) ; 
    þ0E27F . append( ... kids) ; 
     if (attrs)
      𝒪(attrs) . forEach(([k , v]) => {
         if (k == `𝑆`    ) þ0E27F . style . cssText  =  v ; 
         else if (k in remaps) þ0E27F[remaps[k]]  =  v ; 
         else             SAT(þ0E27F , k , v) ;  }) ; 
    
     return þ0E27F ;  } ; 

swapə  =   (x,y,...𝔸)=> {  if (x === y)  return  ; 
            const  [α , β]  =  [x . parentNode , y . parentNode] ; 
            if (α && β) {  let  χ  =  mkə( false  , {} ,  false )
                    α . insertBefore(χ , x) ; 
                    β . insertBefore(x , y) ; 
                    χ . parentNode . insertBefore(y , χ) ; 
                    χ . remove() ;  }
            else if (α) α . replaceChild(y , x) ; 
            else if (β) α . replaceChild(x , y) ;  } ; 