/* AUTOGENERATED */
 const  prompt_token  =  (cb) => {
   const  fld  =  textField({id : `tokenField` , 𝑃𝐻 : `Token` , þ0F070 :  true }) ; 
   const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
          mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column;`} , [
            fld , 
            textButton(`Submit` ,  (...𝔸)=> {þ0E27F . close() ;  cb(fld . 𝚒 . value)})])) ; } ; 

 let  ədevListing  =   (...𝔸)=> {
   const  𝔖  =  {} ; 
   const  ədevTile  =  (𝐮 , 𝐝) => {
     const  þ0E27F  =  mkə( false  ,  false  , [(mkə(`h2` ,  false  , `${𝐮} ${[`🔴` , `🟢`][ + 𝐝 . online]}`)) , (mkə(`h3` ,  false  , `${𝐝 . RGB_ORDER} - ${𝐝 . LEDC} LEDs (${"→←"[ + 𝐝 . REVERSE]})`))])
     return þ0E27F } ; 
   let  þ0E27FdevListing ; 
   const  þ0E27F  =  ətitledBox(`Devices` , 
                   þ0E27FdevListing
                      =  əitemGridEditable(
                          undefined  , 
                         (x , rem) => [ədevTile( ... x) , 
                                 əbuttonBar(
                                   [𝔄[`󰆴`] , rem] , 
                                   [𝔄[``] ,  (...𝔸)=> prompt_rgb_calibrate(𝐀(𝔖 . 𝐭 , x[0]) ,  (x,...𝔸)=> (x , þ0E27F . populate(𝔖 . 𝐭)))] , 
                                   [𝔄[``] ,  (...𝔸)=> prompt_led_calibrate(𝐀(𝔖 . 𝐭 , x[0]) ,  (x,...𝔸)=> (x , þ0E27F . populate(𝔖 . 𝐭)))] , 
                                   [𝔄[`󰐥`] ,  (...𝔸)=> 𝐀(𝔖 . 𝐭) . dev(x[0]) . off()])] , 
                          (x,...𝔸)=>  print (`Removing ${x}`) , 
                         [] , 
                         { show_plus   :   false  , 
                           placeholder :   (...𝔸)=> mkə(`h3` ,  false  , `No devices found for this token...`) })) ; 
  þ0E27FdevListing . style . maxHeight  =  `80vh` ; 
  þ0E27F . populate  =   async  (𝐭) => { 𝔖 . 𝐭  =  𝐭 ; 
                      let  devs  =   await  load_devices(𝔖 . 𝐭) ; 
                     devs  =  devs[1] ; 
                     þ0E27FdevListing . clear_items() ; 
                     𝒪(devs) . forEach( (x,...𝔸)=> þ0E27FdevListing . add_item(x)) ;  } ; 
   return þ0E27F ;  } ; 

 let  ətokenListing  =  (þ0E27FdevListing) => {
   const  ətokenTile  =  (𝐭) => 
      mkə(`div` , {[`𝐶`] : `bigButton` , [`onclick`] :  (...𝔸)=> þ0E27FdevListing . populate(𝐭)} , [(mkə(`h1` ,  false  , [(𝐭)]))])
   let  þ0E27FtokenListing ; 
   let  þ0E27F  =  ətitledBox(
          `Tokens` , 
          þ0E27FtokenListing
             =  əitemGridEditable(
                (  gen) => prompt_token(gen) , 
                (x , rem) => [ətokenTile(x) , əbuttonBar([𝔄[`󰆴`] , rem])] , 
                 (x,...𝔸)=>  print (`Removing ${x}`))) ; 
  þ0E27FtokenListing . style . maxHeight  =  `80vh` ; 
  þ0E27F . populate  =  (𝐓) => { þ0E27FtokenListing . clear_items() ; 
                   𝐓 . forEach((𝐭) => þ0E27FtokenListing . add_item(𝐭)) ;  }
   return þ0E27F ;  }

 const  ətokenDevListing  =  (𝐓) => {
   const  þ0E27FdevListing  =  ədevListing() ; 
   const  þ0E27FtokenListing  =  ətokenListing(þ0E27FdevListing) ; 
  þ0E27FtokenListing . populate(𝐓) ; 
   return mkə(`div` , {[`𝑆`] : `width: 100%; display: flex; flex-direction: column; align-items: center;`} , [þ0E27FtokenListing , þ0E27FdevListing])} ; 

þF0219 . body . append(ətokenDevListing(["testing" , "notrealtoken"])) ; 






