/* AUTOGENERATED */
 const setTok = async (x, ...𝔸) => {
   𝔏𝔖.þ02191(`selTok`, x);
   const devs = await þ0E27FdevListing.populate(x);
   þ0E27FsceneListing.populate(x);
   [`Devices`, `Scenes`, `Schedule`].forEach((x, ...𝔸) => þ0E27Fnav.Ѧ.𝙳[x].𝚋.disabled = false);
   þ0E27Fnav.set(𝒪𝑏(devs, `Devices`, `Scenes`));
 }

 const þ0E27FtokenListing = ətokenListing(setTok);
 const þ0E27FdevListing = ədevListing();
 const þ0E27FsceneListing = əsceneListing((x, ...𝔸) => print(`Scene called ${x}`));

 const toks = get_toks();
 þ0E27FtokenListing.populate(toks);

 let defView = `Tokens`;
 if (toks.length && 𝔏𝔖.þ02193(`selTok`)) {
   setTok(𝔏𝔖.þ02193(`selTok`))
   defView = `Devices`;
 }

 const þ0E27Fnav = mkə(ənavBar, [
   [`Ⴝ`, defView]
 ], [(mkə(`✗`, false, [(mkə(`div`, false, `󰤱 logo`))])), (mkə(false, [
   [`󰊄`, `Tokens`],
   [`disabled`, true]
 ], þ0E27FtokenListing)), (mkə(false, [
   [`󰊄`, `Devices`],
   [`disabled`, true]
 ], þ0E27FdevListing)), (mkə(false, [
   [`󰊄`, `Scenes`],
   [`disabled`, true]
 ], þ0E27FsceneListing)), (mkə(false, [
   [`󰊄`, `Schedule`],
   [`disabled`, true]
 ], [(mkə(`div`, false, `󰤱`))]))]);
 þF0219.body.append(þ0E27Fnav);