/* AUTOGENERATED */
 const setBar = (𝚜) => [`Devices`, `Scenes`, `Schedule`].forEach((x, ...𝔸) => þ0E27Fnav.Ѧ.𝙳[x].𝚋.disabled = !𝚜);
 const setTok = async (𝐭) => {
   const 𝔱 = 𝐀(𝐭);
   𝔏𝔖.þ02191(`selTok`, 𝔱.𝐭);
   const devs = await devListingþ0E27F.Ѧ.populate(𝔱);
   sceneListingþ0E27F.Ѧ.populate(𝔱);
   setBar(true);
   þ0E27Fnav.set(𝒪𝑏(devs, `Devices`, `Scenes`));
 }
 const delTok = (𝐭) => {
   if (𝔏𝔖.þ02193(`selTok`) == 𝐭) 𝔏𝔖.þ02191(`selTok`, undefined);
   setBar(false);
 }

 const tokenListingþ0E27F = ətokenListing({
   ƒ: setTok,
   delƒ: delTok
 });
 const devListingþ0E27F = ədevListing({});
 const sceneListingþ0E27F = əsceneListing({
   ƒ: (Ѧ) => 𝘌run(Ѧ.þF0832, Ѧ.𝐬, Ѧ.𝔱, false, false, -1)
 });
 const sceneShedulerþ0E27F = mkə(`T`, false, `󰤱`);

 const þ0E27Fnav = mkə(ənavBar, [
   [`Ⴝ`, `Tokens`],
   [`top`, true]
 ], [(mkə(`✗`, false, [(mkə(`img`, [
   [`𝑆`, `height: 2em; margin-left: 0.5em;`],
   [`src`, `/Assets/logo.svg`],
   [`alt`, `Logo`]
 ], false))])), (mkə(false, [
   [`󰊄`, `Tokens`]
 ], tokenListingþ0E27F)), (mkə(false, [
   [`󰊄`, `Devices`]
 ], devListingþ0E27F)), (mkə(false, [
   [`󰊄`, `Scenes`]
 ], sceneListingþ0E27F)), (mkə(false, [
   [`󰊄`, `Schedule`]
 ], sceneShedulerþ0E27F))]);
 setBar(false);
 þ0E27Fnav.Ѧ.𝙳.Schedule.𝚋.style.display = `None`;

 tokenListingþ0E27F.Ѧ.populate(get_toks());
 tokenListingþ0E27F.Ѧ.set(𝔏𝔖.þ02193(`selTok`));
 þF0219.body.replaceWith(þ0E27Fnav);