/* AUTOGENERATED */
 let  ətokenListing  =  (cb) => {
   const  prompt_token  =  (cb) => {
     const  fld  =  textField({id : `tokenField` , 𝑃𝐻 : `Token` , þ0F070 :  true }) ; 
     const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
                ətitledBox(
                  `Enter token to add` , 
                  mkə(`div` , {[`𝐶`] : `tokenAddBox` , [`𝑆`] : `max-width: ⅘; display: flex; flex-direction: column;`} , [
                    fld , 
                    textButton(`Submit` ,  (...𝔸)=> {þ0E27F . close() ; cb(fld . 𝚒 . value)})]) , 
                  {outline :  false })) ;  } ; 
   const  ətokenTile  =  (𝐭) => mkə(`div` , {[`𝐶`] : `bigButton` , [`𝑆`] : fit_size(𝐭 , 250) , [`onclick`] :  (...𝔸)=> cb(𝐭)} , 𝐭)
   const  þ0E27F  =  əitemGridEditable(
          (  gen) => prompt_token( (x,...𝔸)=> (layout_from_tok(x) , gen(x))) , 
          (x , rem) => [ətokenTile(x) , əbuttonBar([`󰆴` , rem])] , 
          remove_tok) ; 
  þ0E27F . style . maxHeight  =  `80vh` ; 
  þ0E27F . populate  =  (𝐓) => { þ0E27F . clear_items() ; 
                   𝐓 . forEach((𝐭) => þ0E27F . add_item(𝐭)) ;  }
   return þ0E27F ;  }

 let  ədevListing  =   (...𝔸)=> {
   const  𝔖  =  {} ; 
   const  ədevTile  =  (𝐮 , 𝐝) => {
     const  þ0E27F  =  mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column; font-size: 30px;`} , [(mkə(`T` , {[`𝑆`] : `font-size: 40px;`} , `${𝐮} ${[`🔴` , `🟢`][ + 𝐝 . online]}`)) , (mkə(`T` ,  false  , `${𝐝 . RGB_ORDER} - ${𝐝 . LEDC} LEDs (${"→←"[ + 𝐝 . REVERSE]})`))])
     return þ0E27F } ; 
   const  þ0E27F  =  əitemGridEditable(
           undefined  , 
          (x , rem) => [ədevTile( ... x) , 
                  əbuttonBar(
                    [`󰆴` , rem] , 
                    [`` ,  (...𝔸)=> prompt_rgb_calibrate(𝐀(𝔖 . 𝐭 , x[0]) ,  (x,...𝔸)=> (x , þ0E27F . populate(𝔖 . 𝐭)))] , 
                    [`` ,  (...𝔸)=> prompt_led_calibrate(𝐀(𝔖 . 𝐭 , x[0]) ,  (x,...𝔸)=> (x , þ0E27F . populate(𝔖 . 𝐭)))] , 
                    [`󰐥` ,  (...𝔸)=> 𝐀(𝔖 . 𝐭) . dev(x[0]) . off()])] , 
           (x,...𝔸)=>  print (`Removing ${x}`) , 
          [] , 
          { show_plus   :   false  , 
            placeholder :   (...𝔸)=> mkə(`h2` ,  false  , `No devices found for this token...`) })
  þ0E27F . style . maxHeight  =  `80vh` ; 
  þ0E27F . populate  =   async  (𝐭) => { 𝔖 . 𝐭  =  𝐭 ; 
                      let  devs  =   await  load_devices(𝔖 . 𝐭) ; 
                     devs  =  devs[1] ; 
                     þ0E27F . clear_items() ; 
                     𝒪(devs) . forEach( (x,...𝔸)=> þ0E27F . add_item(x)) ;  } ; 
   return þ0E27F ;  } ; 