/* AUTOGENERATED */
 let  ətileButton  =  (t , cb) => mkə(`div` , {[`𝐶`] : `bigButton` , [`𝑆`] : fit_size(t , 250) , [`onclick`] :  (...𝔸)=> cb(t)} , t)

 let  ətokenListing  =  (cb) => {
   const  prompt_token  =  (cb) => {
     const  fld  =  textField({id : `tokenField` , 𝑃𝐻 : `Token` , þ0F070 :  true }) ; 
     const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
                ətitledBox(
                  `Enter token to add` , 
                  mkə(`div` , {[`𝐶`] : `tokenAddBox` , [`𝑆`] : `max-width: ⅘; display: flex; flex-direction: column;`} , [
                    fld , 
                    textButton(`Submit` ,  (...𝔸)=> {þ0E27F . close() ; cb(fld . 𝚒 . value)})]) , 
                  {outline :  false })) ;  } ; 
   const  þ0E27F  =  əitemGridEditable(
          (  gen) => prompt_token( (x,...𝔸)=> (add_check_tok(x) , gen(x))) , 
          (x , rem) => [ətileButton(x , cb) , əbuttonBar([`󰆴` , rem])] , 
          del_tok) ; 
  þ0E27F . populate  =  (𝐓) => { þ0E27F . clear_items() ; 
                   𝐓 . forEach( (x,...𝔸)=> þ0E27F . add_item(x)) ;  }
   return þ0E27F ;  }

 let  ədevListing  =   (...𝔸)=> {
   const  𝔖  =  {} ; 
   const  ədevTile  =  (𝐮 , 𝐝) => {
     const  þ0E27F  =  mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column; font-size: 30px;`} , [(mkə(`T` , {[`𝑆`] : `font-size: 40px;`} , `${𝐮} ${[`🔴` , `🟢`][ + 𝐝 . online]}`)) , (mkə(`T` ,  false  , `${𝐝 . RGB_ORDER} - ${𝐝 . LEDC} LEDs (${"→←"[ + 𝐝 . REVERSE]})`))])
     return þ0E27F } ; 
   const  þ0E27F  =  əitemGridEditable(
           undefined  , 
          (x , rem) => [ədevTile( ... x) , 
                  əbuttonBar(
                    [`󰆴` , rem                                               ] , 
                    [`` ,  (...𝔸)=> prompt_rgb_calibrate(𝐀(𝔖 . 𝐭 , x[0]) ,  (x,...𝔸)=> (x , þ0E27F . populate(𝔖 . 𝐭)))] , 
                    [`` ,  (...𝔸)=> prompt_led_calibrate(𝐀(𝔖 . 𝐭 , x[0]) ,  (x,...𝔸)=> (x , þ0E27F . populate(𝔖 . 𝐭)))] , 
                    [`󰐥` ,  (...𝔸)=> 𝐀(𝔖 . 𝐭) . dev(x[0]) . off()                              ])] , 
           (x,...𝔸)=>  print (`Removing ${x}`) , 
          [] , 
          { show_plus   :   false  , 
            placeholder :   (...𝔸)=> mkə(`h2` ,  false  , `No devices found for this token...`) })
  þ0E27F . populate  =   async  (𝐭) => { 𝔖 . 𝐭  =  𝐭 ; 
                      let  devs  =   await  load_devices(𝔖 . 𝐭) ; 
                     devs  =  devs[1] ; 
                     þ0E27F . clear_items() ; 
                     𝒪(devs) . forEach( (x,...𝔸)=> þ0E27F . add_item(x)) ;  } ; 
   return þ0E27F ;  } ; 

 let  əsceneListing  =  (cb) => {
   const  𝔖  =  {} ; 
   const  prompt_scene  =  (cb , Ѧ = {name :  ""  , 𝐔 : [] , dat : {}}) => {
     const  fld  =  textField({𝑃𝐻 : `Scene Name` , value : Ѧ . name}) ; 
     const  get  =   (...𝔸)=> ({ ... Ѧ , name : fld . 𝚒 . value}) ; 
     const  þ0E27F  =  popup({þ0F2D4 :  true  , þF0159 :  true } , 
                ətitledBox(
                  `Scene details` , 
                  mkə(`div` , {[`𝐶`] : `tokenAddBox` , [`𝑆`] : `max-width: ⅘; display: flex; flex-direction: column;`} , [
                    fld , 
                    textButton(`Submit` ,  (...𝔸)=> {þ0E27F . close() ; cb(get())})]) , 
                  {outline :  false })) ;  } ; 
   const  þ0E27F  =  əitemGridEditable(
          (  gen) => prompt_scene(
                   (𝐬) => {  if ( ! add_scene(𝔖 . 𝐭 , 𝐬))
                          return  print (`Scene already exists ${x}‽`) ; 
                        gen(𝐬) ;  }) , 
          (𝐬 , rem) => [ətileButton(𝐬 . name , cb) , 
                  əbuttonBar(
                    [`󰆴` , rem] , 
                    [`` ,  (...𝔸)=> prompt_scene(
                      (𝚗) => { rem(𝐬) ; 
                           add_scene(𝔖 . 𝐭 , 𝚗 ,  true ) ; 
                           þ0E27F . add_item(𝚗) ;  } , 
                      𝐬)])] , 
          (𝐬    ) => move_scene(𝔖 . 𝐭 , 𝐬 . name)) ; 
  þ0E27F . populate  =  (𝐭) => { [𝔖 . 𝐭 , 𝔖 . 𝐃]  =  [𝐭 , get_devs(𝐭)] ; 
                   þ0E27F . clear_items() ; 
                   𝒪(get_scenes(𝐭)) . ꟿ((name , y) => þ0E27F . add_item({name ,  ... y})) ;  } ; 
   return þ0E27F ;  }