/* AUTOGENERATED, DO NOT EDIT */
þF0219 . body . append(
    itemGridEditable(
        (gen) => gen(`joe`) , 
        (x , rem) => [mkə( false  , {[`𝑆`] : `width: 100%; display: flex; flex-direction: column;`} , [(mkə(`txt` ,  false  , `${x}`))]) , 
                barButton(`/Assets/trash.svg` ,  {onclick :  rem})] , 
         (x,...𝔸)=>  print (`Removing ${x}`) , 
        [1 , 2 , 3 , 4])) ; 

𝘋𝘉  =  𝔏𝔖 . þ02193("tokens" , {})
updateDB  =   (...𝔸)=> 𝔏𝔖 . þ02191("tokens" , 𝘋𝘉)

layout_from_tok  =  (𝐭) => {
     if ( ! (𝐭 in 𝘋𝘉)) { 𝘋𝘉[𝐭] = { scenes : {} ,  devs : {} } ; 
                 updateDB() ;  }
     return 𝘋𝘉[𝐭] ;  }

load_devices  =   async  (𝐭) => {
     const  𝐋  =  layout_from_tok(𝐭)
     let  r ; 
    try{ r  =   await  api(𝐭 , "Get_devs") ;  }catch(e){}
     if ( ! r[0]  ||  r . status != 200)  return 𝖡(𝐋 . devs) ; 
    𝐋 . devs  =  {  ... 𝐋 . devs ,   ... r[1] . devs }
    updateDB() ; 
     return 𝖦(𝐋 . devs) ;  }

mode  =  { effects :  [𝔠 . Brightness(1) ,  𝔠 . Rotate({speed : 2 ,  offset : 0})] , 
          ... 𝔠 . Modes(
            { effects :  [] ,  
               ... 𝔠 . Atom({leds :  50 ,   ... 𝔠 . Static({clr :  [255 , 0 , 0]})}) } , 
            { effects :  [𝔠 . Rotate({speed :  - 1 ,  offset : 0})] , 
               ... 𝔠 . Atom({leds :  50 ,   ... 𝔠 . Rainbow({segs :  5.0 ,  sat : 255 ,  val : 255})})}) } ; 

 print (load_devices("testing")) ; 






