/* AUTOGENERATED */













þF0832Util  =  {
  len   :  (þF0832) => isArr(þF0832)  ? þF0832[0] :  `1` in þF0832  ? þF0832[`1`] [0] :  þF0832[`*`] . ᴍ( (x,...𝔸)=> þF0832Util . len(x)) . ſ( (x,y,...𝔸)=> x + y , 0) ,  
  grpfx :  (þF0832) => þF0832 . fx  ? ᴍv(þF0832 . fx  . þ0EB86( (x,...𝔸)=> x[0]) ,   (x,...𝔸)=> x . ᴍ( (x,...𝔸)=> x . þF7E3B(1))) :  {} , 
  ends  :  (þF0832) => isArr(þF0832)  ? [þF0832 , þF0832] :  `1` in þF0832  ? [þF0832[`1`] , þF0832[`1`]] :  [þF0832Util . ends(þF0832[`*`] [0])[0] ,  þF0832Util . ends(þF0832[`*`] . at(-1))[1]] , 
  
  defM  :  (C) => ({"*" : C . ᴍ( (x,y,...𝔸)=> ({"1" : [x , 0 , [0xFF0000 , 0xFF00 , 0xFF][y % 3]]})) ,  fx : [[1 , 5 , 0]]}) , 
  
  add   :  (þF0832 , m) => {  if (`1` in þF0832)  return {"*" : [þF0832 , m]} ; 
                þF0832[`*`] . push(m) ; 
                 return þF0832 ;  } , 
  ungrp :  (þF0832 , 𝚒) => { þF0832[`*`]  =  þF0832[`*`] . ᴍþF01A9( (x,y,...𝔸)=> y == 𝚒 ? x[`*`] : [x]) ; 
                 return þF0832 ;  } , 
  foldþ0F0D0 :  (þF0832) => { 
               if ( ! (`fx` in þF0832))  return þF0832 ; 
               if ( !  þF0832 . fx  . length  )  return ( delete  þF0832 . fx , þF0832) ; 
               let  þ0F0D0  =  þF0832Util . grpfx(þF0832) ; 
               if (`0` in þ0F0D0  &&  þ0F0D0[`0`] . length & 2)  delete  þ0F0D0[`0`] ; 
              þ0F0D0  =  ᴍv(þ0F0D0 , (v , k) => {  if (k == `0`)  return v ; 
                               if (k == `1`)  return v . ſ( (x,y,...𝔸)=> [x[0] + y[0] , x[1] + y[1]] , [1 , 0]) ; 
                               if (k == `2`)  return v . ſ( (x,y,...𝔸)=> [x[0] * y[0]] , [1]) ;  }) ; 
               if (`1` in þ0F0D0  &&  þ0F0D0[`1`] [0] == 0  &&  þ0F0D0[`1`] [1] == 0)  delete  þ0F0D0[`1`] ; 
               if (`2` in þ0F0D0  &&  þ0F0D0[`2`] [0] == 1)  delete  þ0F0D0[`2`] ; 
              þF0832 . fx  =  𝒪(þ0F0D0) . ꟿ( (x,y,...𝔸)=> [ + x ,  ... y]) ; 
               return þF0832 ;  } , 
  rm1Gs :  (þF0832) => {  while (`*` in þF0832  &&  þF0832[`*`] . length == 1) {
                 const  β  =  þF0832[`*`] [0] ; 
                 if ((þF0832 . fx ?? []) . length  &&  (β . fx ?? []) . length)
                  þF0832 . fx  =  [ ... þF0832 . fx ?? [] ,   ... β . fx ?? []] ; 
                 if (`1` in β) {  delete  þF0832[`*`] ;  þF0832[`1`]  =  β[`1`] ;   break  ;  }
                þF0832[`*`]  =  β[`*`] ;  }
               return þF0832Util . foldþ0F0D0(þF0832) ;  } , 
  del   :  (þF0832 , 𝚒) => { þF0832[`*`] . splice(𝚒 , 1) ; 
                 return þF0832Util . rm1Gs(þF0832) ;  } } ; 

𝘌run  =  (þF0832 , 𝐬 , 𝔖) => {  const  M  =  {mode : þF0832 ,  offsets : 𝒟( þF147C (𝐬 . 𝐔 , 𝐬 . 𝐔  . Ϝ( (x,y,...𝔸)=> x + 𝔖 . 𝐃[y] . LEDC , 0)))} ; 
                𝐀(𝔖 . 𝐭 ,  ... 𝐬 . 𝐔) . scene(𝐬 . name , M ,  false  , -1) ;  }